"""Domain records for the game platform.

Records are immutable: the service builds updated copies with `dataclasses.replace` and
writes them back to the store, so a store never shares mutable state with its callers.
"""

import datetime as dt
from dataclasses import dataclass
from typing import Final, Literal

from pydantic import JsonValue

MIN_PLAYERS: Final = 2
MAX_PLAYERS: Final = 10

MatchStatus = Literal["waiting_for_players", "ongoing", "over"]
SeatKind = Literal["human", "computer"]
EndReason = Literal["finished", "player_left"]


@dataclass(frozen=True, kw_only=True)
class User:
    id: str
    display_name: str
    # Generated by the server and kept as is, in memory and in the data file. The API
    # returns it from [POST /users] and the debug tools only.
    password: str
    created_at: dt.datetime
    updated_at: dt.datetime


@dataclass(frozen=True, kw_only=True)
class GameRules:
    """The parts of a game that the server enforces during a match."""

    allowed_player_counts: tuple[int, ...]
    allows_leave_mid_match: bool
    allows_join_mid_match: bool

    @property
    def max_players(self) -> int:
        return max(self.allowed_player_counts)


@dataclass(frozen=True, kw_only=True)
class Game:
    """One version of a game. Every update creates a new version."""

    id: str
    # Starts at 1 and increases by one with every update.
    version: int
    owner_user_id: str
    name: str
    description: str
    rules: GameRules
    # The game's client code (the innerHTML of its sandboxed iframe). The server never
    # executes it.
    code: str
    created_at: dt.datetime
    updated_at: dt.datetime
    # Applies to the whole game, so it is set on every version read back from the store
    # once the game is deleted. Deleted games are kept because matches may use them.
    deleted: bool = False


@dataclass(frozen=True, kw_only=True)
class Seat:
    player_index: int
    kind: SeatKind
    # Set exactly when [kind] is "human".
    user_id: str | None


@dataclass(frozen=True, kw_only=True)
class Move:
    move_number: int
    player_index: int
    made_by_user_id: str
    created_at: dt.datetime
    new_state: JsonValue
    # The seats that may make the next move; [None] ends the match.
    next_turn_player_indices: frozenset[int] | None


@dataclass(frozen=True, kw_only=True)
class Match:
    id: str
    game_id: str
    owner_user_id: str
    # The game version the match was created with. Its rules (and code) apply for the
    # whole match, even if the game is later updated or deleted.
    game_version: int
    status: MatchStatus
    seats: tuple[Seat, ...]
    state: JsonValue
    # The seats that may move now; [None] when the match isn't ongoing.
    turn_of_player_indices: frozenset[int] | None
    end_reason: EndReason | None
    moves: tuple[Move, ...]
    # Non-owners who "deleted" this match after it ended; it is excluded from their
    # match list only.
    hidden_for_user_ids: frozenset[str]
    created_at: dt.datetime
    updated_at: dt.datetime

    def seat_of(self, user_id: str) -> Seat | None:
        return next((seat for seat in self.seats if seat.user_id == user_id), None)

    @property
    def human_user_ids(self) -> tuple[str, ...]:
        return tuple(seat.user_id for seat in self.seats if seat.user_id is not None)

    @property
    def num_computer_opponents(self) -> int:
        return sum(1 for seat in self.seats if seat.kind == "computer")

    def involves(self, user_id: str) -> bool:
        return user_id == self.owner_user_id or self.seat_of(user_id) is not None
